version: '3'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      DB_NAME: 'db_name'
      DB_USER: 'db_user'
      DB_PASSWORD: 'db_password'
      DB_HOST: 'db_host'
      DB_PORT: '5432'
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: 'db_name'
      POSTGRES_USER: 'db_user'
      POSTGRES_PASSWORD: 'db_password'
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
